### ISSUE TITLE
can pip install work with gcc 4.8.5?

### ISSUE THREAD

**Issue by demongolem-biz** [google/jsonnet#964]
When I pip install this, I get an error saying that GCC < 5 is not supported.  I really am stuck with 4.8.5 and looked into what it would take to do a local build of GCC >= 5.  

>   g++ -c -g -O3 -Wall -Wextra -Woverloaded-virtual -pedantic -std=c++0x -fPIC -Iinclude -Ithird_party/md5 -Ithird_party/json -Ithird_party/rapidyaml/rapidyaml/src/ -Ithird_party/rapidyaml/rapidyaml/ext/c4core/src/ core/vm.cpp -o core/vm.o
>   In file included from third_party/rapidyaml/rapidyaml/ext/c4core/src/c4/config.hpp:35:0,
>                    from third_party/rapidyaml/rapidyaml/ext/c4core/src/c4/substr.hpp:10,
>                    from third_party/rapidyaml/rapidyaml/ext/c4core/src/c4/std/string.hpp:6,
>                    from third_party/rapidyaml/rapidyaml/src/c4/yml/std/string.hpp:7,
>                    from third_party/rapidyaml/rapidyaml/src/./c4/yml/std/std.hpp:4,
>                    from third_party/rapidyaml/rapidyaml/src/ryml_std.hpp:4,
>                    from core/vm.cpp:29:
>   third_party/rapidyaml/rapidyaml/ext/c4core/src/c4/compiler.hpp:90:13: error: #error "GCC < 5 is not supported"
>    #           error "GCC < 5 is not supported"

**Comment by sparkprime** [comment]
I guess you'd have to build it without YAML support somehow.  Have you tried `pip install gojsonnet` ?

**Comment by demongolem-biz** [comment]
For pip install gojsonnet I get:

error: [Errno 2] No such file or directory: 'go': 'go'

**Comment by sparkprime** [comment]
Ah yes you would need the go toolchain...  Is that easier to obtain than a recent GCC? :)

**Comment by sparkprime** [comment]
I'm wondering what your situation is that you're limited by gcc version? Are you on an embedded system or something?

**Comment by demongolem-biz** [comment]
So my situation is RHEL 7.6 comes with gcc 4.8.5.  And I don't have root access.  I finally was able to get a local copy of gcc and g++ 5.3.0.  I am wondering which version exactly would be recommended because when I install from pip with the 5.3.0 version being invoked I get a bunch of red, to start with:

`third_party/json/json.hpp:236:54: error: ‘to_string’ is not a member of ‘std’`  and `error: ‘snprintf’ is not a member of ‘std’
`

**Comment by demongolem-biz** [comment]
Ok with 6.3.0 rpm that I was able to install locally, it worked.  I was able finally `pip install jsonnet`.  And all this because originally I wanted to `pip install allennlp` which uses jsonnet.

**Comment by MuhammedGenco94** [comment]
Here is an already Compiled & Built [JSONNET](https://mega.nz/file/cy4VzKKR#DMC86fZ8GNfHYVOzTo5KtAqXW261GYd_uhPcwQyaSFE) zipped folder. 

You can use jsonnet command directly by this, like:
`jsonnet input.jsonnet -o output.json`
